<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovo" failures="2" tests="8" name="Test" time="1.138" errors="0" timestamp="2022-11-19T18:49:21 IST">
  <testcase classname="com.Runner_After.TestNG_Retry" name="username" time="0.282">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="username" time="0.012">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="username" time="0.022">
    <skipped/>
  </testcase> <!-- username -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="username" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [Sharon Vithya] but found [Angel Nithy]">
      <![CDATA[java.lang.AssertionError: expected [Sharon Vithya] but found [Angel Nithy]
at com.Runner_After.TestNG_Retry.username(TestNG_Retry.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- username -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="password" time="0.011">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="password" time="0.015">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="password" time="0.05">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.Runner_After.TestNG_Retry" name="password" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [sharon@123] but found [angel@123]">
      <![CDATA[java.lang.AssertionError: expected [sharon@123] but found [angel@123]
at com.Runner_After.TestNG_Retry.password(TestNG_Retry.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- password -->
</testsuite> <!-- Test -->
